USE [master]
GO

/****** Object:  Database [UserDB]    Script Date: 10/7/2022 13:39:25 ******/
CREATE DATABASE [UserDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'UserDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\UserDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'UserDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\UserDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [UserDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [UserDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [UserDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [UserDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [UserDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [UserDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [UserDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [UserDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [UserDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [UserDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [UserDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [UserDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [UserDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [UserDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [UserDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [UserDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [UserDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [UserDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [UserDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [UserDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [UserDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [UserDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [UserDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [UserDB] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [UserDB] SET  MULTI_USER 
GO

ALTER DATABASE [UserDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [UserDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [UserDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [UserDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [UserDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [UserDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [UserDB] SET QUERY_STORE = OFF
GO

ALTER DATABASE [UserDB] SET  READ_WRITE 
GO


